name: linting, testing, building
on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]
jobs:
    pipeline:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Staring Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install modules
              run: yarn install
            - name: build production project
              run: yarn build:prod
              if: always()
            - name: linting typescript
              run: yarn lint:ts
              if: always()
            - name: linting css
              run: yarn lint:scss
            - name: unit testing
              if: always()
              run: yarn test:unit
            - name: build storybook
              run: yarn storybook:build
            - name: screenshot testing
              run: yarn test:ui:ci
